services:
  nginx_http:
    image: nginx:alpine
    container_name: nginx_http
    volumes:
      - ./nginx/nginx.http.conf:/etc/nginx/conf.d/default.conf
      - certbot_data:/var/www/certbot
    ports:
      - "80:80"

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: >- 
             certonly --webroot --webroot-path=/var/www/certbot
             --email ${EMAIL} --agree-tos --no-eff-email
             -d ${DOMAIN} --non-interactive --quiet
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - certbot_data:/var/www/certbot
    depends_on:
      - nginx_http

  nginx_https:
    image: nginx:alpine
    container_name: nginx_https
    volumes:
      - ./nginx/nginx.https.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"
    depends_on:
      certbot:
        condition: service_completed_successfully

volumes:
  certbot_data: